### ISSUE TITLE
`201 - Created` leads to failed Job. Why? 

### ISSUE THREAD

**Issue by langsmith** [ALJAZEERAPLUS/sauce-labs-storage-action#9]
Thanks for this `Action`. I've got it up and running to upload my Android app APK to my SauceLab account. After it uploads, the `201` is causing GitHub to mark the run as failed 🤔  Any idea why? Any way to fix this? 

---------------------

`Error: Unexpected error: Unexpected status: 201 - Created`

<img width="699" alt="Screenshot 2023-12-18 at 3 59 46 PM" src="https://github.com/ALJAZEERAPLUS/sauce-labs-storage-action/assets/4394910/498f728a-48db-46d4-b406-6c696ff70d90">

---------------------

<img width="559" alt="Screenshot 2023-12-18 at 4 02 41 PM" src="https://github.com/ALJAZEERAPLUS/sauce-labs-storage-action/assets/4394910/a13b74b1-2a0c-4c00-8e22-184214a7334e">

---------------------

<img width="624" alt="Screenshot 2023-12-18 at 4 02 46 PM" src="https://github.com/ALJAZEERAPLUS/sauce-labs-storage-action/assets/4394910/efaf39c4-e4ff-48ea-bd86-37753758329f">

**Comment by langsmith** [comment]
@vhsantos26 , @AJ-Digital-platforms , any ideas why this might be happening? What the fix is?

**Comment by vhsantos26** [comment]
@langsmith, thanks a lot for highlighting this issue.

Sorry for the delay in responding. We will look at it and let you know the root cause and a possible fix. 

--- 

Question: Is the file uploaded?

**Comment by langsmith** [comment]
Yea, the file actually does successfully make it to my Sauce Labs account.

**Comment by vhsantos26** [comment]
@langsmith, thanks for that. We will try to reproduce it, but today, we are not facing this issue.  Is there any particular thing on the APK build that could help know the issue?

**Comment by langsmith** [comment]
Nah, I don't think there's anything particularly strange or special about the APK. This is what runs before the Sauce Labs upload. The file has other stuff after Sauce Labs, but that's probably irrelevant because it's all happening after the Sauce Labs step.

```yml

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Build release APK, upload to SauceLabs, and potentially to S3
    runs-on: ubuntu-latest
    steps:
    - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"

    - uses: actions/checkout@v4
    
    - run: echo "The ${{ github.repository }} repository has been cloned"
    
    - run: echo "Setting up JDK" 
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - run: echo "The workflow is now ready to test your code."
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Bump versionCode
      uses: chkfung/android-version-actions@v1.2.3
      with:
        gradlePath: app/build.gradle.kts 
        versionCode: ${{github.run_number}}

    - name: Capture Gradle Version Name and Code
      shell: bash
      run: |
        versionName=$(sed -n 's/^[[:space:]]*versionName = "\([^"]*\)"/\1/p' app/build.gradle.kts)
        echo "VERSION_NAME=$versionName" >> $GITHUB_ENV
        versionCode=$(sed -n 's/^[[:space:]]*versionCode = \(.*\)/\1/p' app/build.gradle.kts)
        echo "VERSION_CODE=$versionCode" >> $GITHUB_ENV

    - name: Run testReleaseUnitTest
      run: ./gradlew testReleaseUnitTest

    - run: echo "testReleaseUnitTest status report=${{ job.status }}."

    - run: echo "Building release APK"

    - name: Run assembleRelease
      run: ./gradlew assembleRelease
      env:
        SDK_KEY_1: ${{ secrets.SDK_KEY_1 }}
        SDK_KEY_2: ${{ secrets.SDK_KEY_2 }}
        SDK_KEY_3: ${{ secrets.SDK_KEY_3 }}

    - name: Set up Android build tools
      shell: bash
      run: |
        BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
        echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
        echo Last build tool version is: $BUILD_TOOL_VERSION

    - name: Sign release APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

    - name: Upload APK to the SauceLabs
      id: upload-task
      if: github.ref == 'refs/heads/main'
      continue-on-error: true
      uses: ALJAZEERAPLUS/sauce-labs-storage-action@v2
      with:
        endpoint-action: upload
        upload-file-path: FILE_PATH
        upload-artifact-description: Uploading from GitHub repository!
        sauce-labs-username: ${{ secrets.SAUCELABS_USERNAME }}
        sauce-labs-access-key: ${{ secrets.SAUCELABS_ACCESS_KEY }}

    - run: echo "Result of upload task was '${{ steps.upload-task.outcome }}'. If it failed because of an unexpected 201 Created status, then it actually succeeded and is on Sauce Labs. Disregard the Error/fail outcome. It's a bug with the 3rd party storage action."
      if: github.ref == 'refs/heads/main'
```

**Comment by vhsantos26** [comment]
@langsmith, thanks for sharing it. We were able to reproduce it. We will work to resolve it as soon as possible.

**Comment by langsmith** [comment]
Oh, cool that you were able to reproduce it. Thanks for looking in to all of this.

**Comment by vhsantos26** [comment]
@langsmith, the issue was resolved on the release [v2.2.0](https://github.com/ALJAZEERAPLUS/sauce-labs-storage-action/releases/tag/v2.2.0).

**Comment by langsmith** [comment]
Great, thanks @vhsantos26 !

**Comment by langsmith** [comment]
@vhsantos26 , I'm still getting the failure with `ALJAZEERAPLUS/sauce-labs-storage-action@v2`. Should I be doing something differently than what I'm currently doing 👇🏽 ? Some thing in particular to get access to `2.2.0`?

```yml
- name: Upload APK to the SauceLabs
      id: upload-task
      if: github.ref == 'refs/heads/main'
      continue-on-error: true
      uses: ALJAZEERAPLUS/sauce-labs-storage-action@v2
      with:
        endpoint-action: upload
        upload-file-path: app_path.apk
        upload-artifact-description: Uploading from GitHub repository!
        sauce-labs-username: ${{ secrets.SAUCELABS_USERNAME }}
        sauce-labs-access-key: ${{ secrets.SAUCELABS_ACCESS_KEY }}
```

**Comment by langsmith** [comment]
Thoughts @vhsantos26 ?
